// React/src/components/LastTransactions.js
/**
 * Created by Joel on 24.04.2017.
 */
// @flow

import React from 'react'

import type {getTransactions, Transaction} from '../api'

import { Link } from 'react-router-dom'

export type Props = {
  token: string,
}

function TransactionsTable({transactions}) {
  const tableEntry = (trans: Transaction) => <tr>
    <th scope="row">{trans.from}</th>
    <td>{trans.target}</td>
    <td>{trans.amount.toFixed(2)} CHF</td>
    <td>{trans.total.toFixed(2)} CHF</td>
  </tr>;
  return <table className="table table-striped table-responsive">
    <thead className="thead-inverse">
    <th>Von</th>
    <th>Zu</th>
    <th>Betrag</th>
    <th>Kontostand Neu</th>
    </thead>
    {transactions.map(tableEntry)}
  </table>
}

class LastTransactions extends React.Component {

  props: Props;

  state: {
    transactions: Array<Transaction>,
  };

  constructor(props) {
    super(props);
    this.props = props;
    getTransactions(props.token).then(result => this.setState({transactions: result}));
  }

  render() {
    return (
      <div className="card">
        <h1 className="card-header">Letzte Bewegungen</h1>
        <div className="card-block">
          <TransactionsTable transactions={this.state.transactions}/>
          <Link className="btn btn-primary" to="/transactions">Alle Anzeigen</Link>
        </div>
      </div>
    )
  }
}

export default LastTransactions

// Angular/MyAngularBanking/src/app/dashboard/components/last-transactions.component.ts
/**
 * Created by Joel on 31.03.2017.
 */

import {Component} from '@angular/core';
import {Transaction} from "../models";
import {BankingService} from "../services";

@Component({
  selector: 'wed-last-transactions',
  templateUrl: 'last-transactions.component.html',
  styleUrls: ['last-transactions.component.scss']
})
export class LastTransactionsComponent {
  public lastTransactions: Array<Transaction>;

  constructor(private bankSvc: BankingService) {
    this.bankSvc.getLastN(3).subscribe(
      (data: Array<Transaction>) => {
        this.lastTransactions = data;
      }
    );;
  }
}

<div class="card">
  <h1 class="card-header">Letzte Bewegungen</h1>
  <div class="card-block">
    <table class="table table-striped table-responsive col-12">
      <thead class="thead-inverse">
        <th>Von</th>
        <th>Zu</th>
        <th>Betrag</th>
        <th>Kontostand Neu</th>
      </thead>
      <tr *ngFor="let trans of lastTransactions">
        <th scope="row">{{trans.from}}</th>
        <td>{{trans.to}}</td>
        <td>{{trans.amount | number: '1.2-2'}} CHF</td>
        <td>{{trans.balance | number: '1.2-2'}} CHF</td>
      </tr>
    </table>
    <button class="btn btn-primary" routerLink="transactions">Alle Anzeigen</button>
  </div>
</div>
