// React/src/components/NewTransaction.js
/**
 * Created by Joel on 24.04.2017.
 */
// @flow

import React from 'react'

import type { User } from '../api'

export type Props = {
    token: string,
    user: User,
}

class NewTransaction extends React.Component {

    props: Props;

    render() {
        return (
            <div>
                <h1>Neue Bewegung</h1>
                <form>
                <div class="form-group">
                    <label for="fromAccount">Von</label>
                    <select id="fromAccount" class="form-control" disabled>
                        <option>{{accountDetails.accountNr}} [{{accountDetails.amount | number: '1.2-2'}}]</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="toAccount">Zu</label>
                    <input type="number" class="form-control" id="toAccount" name="toAccountNr" placeholder="Ziel Konto Nummer" aria-describedby="toAccountHelp" ngModel>
                        <span id="toAccountHelp" class="help-block">{{getValidationTextToAccount()}}</span>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="amount">Betrag (in Schweizerfranken)</label>
                    <div class="input-group">
                        <div class="input-group-addon">CHF</div>
                        <input type="number" class="form-control" id="amount" name="amount" placeholder="Betrag" ngModel>
                    </div>
                </div>
                <button class="btn btn-primary">Zahlen</button>
            </form>
            </div>
        )
    }
}

export default NewTransaction

// Angular/MyAngularBanking/src/app/dashboard/components/new-transaction.component.ts
/**
 * Created by Joel on 31.03.2017.
 */

import {Component} from '@angular/core';
import {Account} from '../../auth/models/account';
import {Transaction} from '../models/transaction';
import {BankingService} from "../services/banking.service";
import {AccountService} from "../services/account.service";

@Component({
  selector: 'wed-new-transaction',
  templateUrl: 'new-transaction.component.html',
  styleUrls: ['new-transaction.component.scss']
})
export class NewTransactionComponent {

  public account: Account;
  public lastTransaction: Transaction;
  public toAccountNr: number;
  public amount: number;

  constructor(private bankSvc: BankingService, private accSvc: AccountService) {

  }

  public isValidTransaction(): boolean {
    return false;
  }

  public getValidationTextToAccount(): string {
    return 'test';
  }

  public addNewTransaction() {
    this.bankSvc.addNewTransaction(new Transaction(new Date(Date.now()), this.account, this.accSvc.getAccount(this.toAccountNr), this.amount, 0));
  }
}

<h1>Neue Bewegung</h1>
<form>
  <div class="form-group">
    <label for="fromAccount">Von</label>
    <select id="fromAccount" class="form-control" disabled>
      <option>{{account.accountNr}}</option>
    </select>
  </div>
  <div class="form-group">
    <label for="toAccount">Zu</label>
    <input type="number" class="form-control" id="toAccount" [(ngModel)]="toAccountNr" placeholder="Ziel Konto Nummer" aria-describedby="toAccountHelp">
    <span id="toAccountHelp" class="help-block">{{getValidationTextToAccount()}}</span>
  </div>
  <div class="form-group">
    <label class="sr-only" for="amount">Betrag (in Schweizerfranken)</label>
    <div class="input-group">
      <div class="input-group-addon">CHF</div>
      <input type="number" class="form-control" id="amount" [(ngModel)]="amount" placeholder="Betrag">
    </div>
  </div>
  <button type="submit" class="btn btn-default">Zahlen</button>
</form>
